# Please keep in sync with requirements.txt in /generic
name: fmu_env
dependencies:
- python=3.7
- pip
- pyyaml==5.4.1
- pip:
  - microsoft-bonsai-api==0.1.3
  - bonsai-cli==1.0.12
  - python-dotenv==0.13.0
  - fmpy==0.2.27
